# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from typing import Literal
import asyncio


class Ui_Interface(object):
    def __init__(self, *, version:str="0") -> None:
        self.version:str = version
    
    async def setupUi(self, Interface:QtWidgets.QMainWindow) -> None:
        
        Interface.setObjectName("Interface")
        Interface.resize(512, 241)
        
        self.telas = QtWidgets.QStackedWidget(Interface)
        self.telas.setGeometry(QtCore.QRect(10, 10, 491, 221))
        self.telas.setObjectName("telas")
        
        self.pg01_inicial = QtWidgets.QWidget()
        self.pg01_inicial.setObjectName("pg01_inicial")
        
        self.pg01_bt_carregar_arquivo = QtWidgets.QPushButton(self.pg01_inicial)
        self.pg01_bt_carregar_arquivo.setGeometry(QtCore.QRect(140, 130, 211, 41))
        self.pg01_bt_carregar_arquivo.setObjectName("pg01_bt_carregar_arquivo")
        
        self.pg01_label_titulo = QtWidgets.QLabel(self.pg01_inicial)
        self.pg01_label_titulo.setGeometry(QtCore.QRect(20, 20, 461, 81))
        self.pg01_label_titulo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter) #type: ignore
        self.pg01_label_titulo.setObjectName("pg01_label_titulo")
        
        self.pg01_label_aviso = QtWidgets.QLabel(self.pg01_inicial)
        self.pg01_label_aviso.setGeometry(QtCore.QRect(20, 180, 461, 40))
        self.pg01_label_aviso.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter) #type: ignore
        self.pg01_label_aviso.setObjectName("pg01_label_aviso")
        #self.pg01_label_aviso.setStyleSheet("color: red")
        self.pg01_label_aviso.setVisible(False)
        
        self.telas.addWidget(self.pg01_inicial)
        
        self.pg02_pos_inicial = QtWidgets.QWidget()
        self.pg02_pos_inicial.setObjectName("pg02_pos_inicial")
        
        self.pg02_bt_verific_empre = QtWidgets.QPushButton(self.pg02_pos_inicial)
        self.pg02_bt_verific_empre.setGeometry(QtCore.QRect(20, 10, 141, 31))
        self.pg02_bt_verific_empre.setObjectName("pg02_bt_verific_empre")
        
        self.pg02_bt_iniciar = QtWidgets.QPushButton(self.pg02_pos_inicial)
        self.pg02_bt_iniciar.setGeometry(QtCore.QRect(20, 60, 141, 31))
        self.pg02_bt_iniciar.setVisible(False)
        self.pg02_bt_iniciar.setObjectName("pg02_bt_iniciar")
        
        self.pg02_bt_voltar = QtWidgets.QPushButton(self.pg02_pos_inicial)
        self.pg02_bt_voltar.setGeometry(QtCore.QRect(20, 110, 141, 31))
        self.pg02_bt_voltar.setObjectName("pg02_bt_voltar")
        #self.pg02_bt_voltar.setVisible(False)
        
        self.pg02_lista_empresas = QtWidgets.QListWidget(self.pg02_pos_inicial)
        self.pg02_lista_empresas.setGeometry(QtCore.QRect(200, 10, 256, 141))
        self.pg02_lista_empresas.setObjectName("pg02_lista_empresas")
        
        self.pg02_label_infor_text = QtWidgets.QLabel(self.pg02_pos_inicial)
        self.pg02_label_infor_text.setGeometry(QtCore.QRect(10, 160, 471, 51))
        self.pg02_label_infor_text.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.pg02_label_infor_text.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.pg02_label_infor_text.setLineWidth(1)
        self.pg02_label_infor_text.setMidLineWidth(0)
        self.pg02_label_infor_text.setTextFormat(QtCore.Qt.TextFormat.AutoText) #type: ignore
        self.pg02_label_infor_text.setScaledContents(False)
        self.pg02_label_infor_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter) #type: ignore
        self.pg02_label_infor_text.setWordWrap(False)
        self.pg02_label_infor_text.setOpenExternalLinks(False)
        self.pg02_label_infor_text.setObjectName("pg02_label_infor_text")
        
        
        self.telas.addWidget(self.pg02_pos_inicial)

        await self.retranslateUi(Interface)
        self.telas.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Interface)

    async def retranslateUi(self, Interface:QtWidgets.QMainWindow) -> None:
        _translate = QtCore.QCoreApplication.translate
        Interface.setWindowTitle(_translate("Interface", f"Automação Geração das Guias RET V{self.version}"))
        self.pg01_bt_carregar_arquivo.setText(_translate("Interface", "Carregar Arquivo"))
        self.pg01_label_titulo.setText(_translate("Interface", "Selecione o arquivo excel padrão."))
        self.pg01_label_aviso.setText(_translate("Interface", "Aviso"))
        self.pg02_bt_verific_empre.setText(_translate("Interface", "Verificar Empresas"))
        self.pg02_bt_iniciar.setText(_translate("Interface", "Iniciar"))
        self.pg02_bt_voltar.setText(_translate("Interface", "Voltar"))
        self.pg02_label_infor_text.setText(_translate("Interface", " "))
        
        
    async def mudar_pagina(self, pagina:Literal["Inicial", "Pos-Inicial"]) -> None:
        if pagina == 'Inicial':
            self.telas.setCurrentIndex(0)
        elif pagina == "Pos-Inicial":
            self.telas.setCurrentIndex(1)
            
    async def pg01_print_aviso(self, *, reset: bool=False, text:str="", color:Literal["black", "red"]="black") -> None:
        if reset:
            self.pg01_label_aviso.setVisible(False)
            self.pg01_label_aviso.setStyleSheet("color:black")
            self.pg01_label_aviso.setText("")
        else:
            text = str(text)
            self.pg01_label_aviso.setStyleSheet(f"color: {color}")
            self.pg01_label_aviso.setText(text)
            self.pg01_label_aviso.setVisible(True)
            
    async def pg02_print_infor(self, *, reset: bool=False, text:str="", color:Literal["black", "red"]="black") -> None:
        if reset:
            #self.pg02_label_infor_text.setVisible(False)
            self.pg02_label_infor_text.setStyleSheet("color:black")
            self.pg02_label_infor_text.setText("")
        else:
            text = str(text)
            self.pg02_label_infor_text.setStyleSheet(f"color: {color}")
            self.pg02_label_infor_text.setText(text)
            #self.pg02_label_infor_text.setVisible(True)
        await asyncio.sleep(.1)
            
    async def pg02_list_additem(self, text:str) -> None:
        self.pg02_lista_empresas.addItem(QtWidgets.QListWidgetItem())
        self.pg02_lista_empresas.item(self.pg02_lista_empresas.count() - 1).setText(str(text))# type: ignore
        
    async def pg02_list_limpar_items(self) -> None:
        if (num_items:=self.pg02_lista_empresas.count()) > 0:
            for _ in range(num_items):
                self.pg02_lista_empresas.takeItem(0)
                
    async def pg02_bt_verific_visibilidade(self, visible:bool) -> None:
        self.pg02_bt_verific_empre.setVisible(visible)
        self.pg02_bt_voltar.setVisible(visible)
    
    async def pg01_bt_carregar_arquivo_visibilidade(self, visible:bool) -> None:
        self.pg01_bt_carregar_arquivo.setVisible(visible)
        
    async def pg02_bt_iniciar_visibilidade(self, visible) -> None:
        self.pg02_bt_iniciar.setVisible(visible)
            
        
        
if __name__ == "__main__":
    pass
